version: '3'
services:
  nginx:
   container_name: v-nginx
   image: nginx:1.13
   restart: always
   ports:
   - 80:80
   - 443:443
   volumes:
   - ./nginx/conf.d:/etc/nginx/conf.d

  mysql:
   container_name: v-mysql
   image: mysql:5.7.22
   environment:
    MYSQL_DATABASE: test
    MYSQL_ROOT_PASSWORD: 123456
    MYSQL_ROOT_HOST: '%'
   ports:
   - 3306:3306
   restart: always

  app:
    restart: always
    build: ./spring-boot-docker-compose
    working_dir: /spring-boot-docker-compose
    volumes:
      - ./spring-boot-docker-compose:/app
      - ~/.m2:/root/.m2
    expose:
      - 8080
    depends_on:
      - nginx
      - mysql
    command: mvn clean spring-boot:run -Dspring-boot.run.profiles=docker